<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xbx.study</groupId>
        <artifactId>AI</artifactId>
        <version>1.0</version>
    </parent>
    <groupId>com.xbx.study.springai</groupId>
    <artifactId>AI-SpringAi</artifactId>
    <packaging>jar</packaging>
    <name>AI-SpringAi</name>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>
    <build>
        <finalName>AI-SpringAi</finalName>
    </build>
</project>
