<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xbx.study</groupId>
        <artifactId>cloud</artifactId>
        <version>1.0</version>
    </parent>
    <artifactId>AI</artifactId>
    <packaging>pom</packaging>
    <name>AI Projects</name>
    <modules>
        <module>AI-LangChain4j</module>
        <module>AI-copilotkit-project</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <langchain.version>1.16.3</langchain.version>
        <langchain.community.version>1.17.2-beta27</langchain.community.version>
        <langchain.springboot.version>1.16.3-beta26</langchain.springboot.version>
    </properties>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
                <version>${langchain.springboot.version}</version>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-spring-boot-starter</artifactId>
                <version>${langchain.springboot.version}</version>
            </dependency>

            <!-- langchain4j-bom -->
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-bom</artifactId>
                <version>${langchain.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>dev.langchain4j</groupId>
                <artifactId>langchain4j-community-bom</artifactId>
                <version>${langchain.community.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <finalName>AI</finalName>
    </build>
</project>
