// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync_message.proto
// Protobuf Java Version: 4.35.0

package com.xbx.study.netty.protobuf;

@com.google.protobuf.Generated
public final class SyncMessageProto extends com.google.protobuf.GeneratedFile {
  private SyncMessageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 0,
      /* suffix= */ "",
      "SyncMessageProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 消息类型枚举
   * </pre>
   *
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MESSAGE_UNKNOWN = 0;</code>
     */
    MESSAGE_UNKNOWN(0),
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>HEARTBEAT = 1;</code>
     */
    HEARTBEAT(1),
    /**
     * <pre>
     * 用户相关
     * </pre>
     *
     * <code>USER_QUERY = 2;</code>
     */
    USER_QUERY(2),
    /**
     * <pre>
     * 按业务扩展...
     * </pre>
     *
     * <code>USER_CREATE = 3;</code>
     */
    USER_CREATE(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "MessageType");
    }
    /**
     * <code>MESSAGE_UNKNOWN = 0;</code>
     */
    public static final int MESSAGE_UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * 心跳
     * </pre>
     *
     * <code>HEARTBEAT = 1;</code>
     */
    public static final int HEARTBEAT_VALUE = 1;
    /**
     * <pre>
     * 用户相关
     * </pre>
     *
     * <code>USER_QUERY = 2;</code>
     */
    public static final int USER_QUERY_VALUE = 2;
    /**
     * <pre>
     * 按业务扩展...
     * </pre>
     *
     * <code>USER_CREATE = 3;</code>
     */
    public static final int USER_CREATE_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return MESSAGE_UNKNOWN;
        case 1: return HEARTBEAT;
        case 2: return USER_QUERY;
        case 3: return USER_CREATE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.getDescriptor().getEnumType(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }

  /**
   * <pre>
   * 响应状态码
   * </pre>
   *
   * Protobuf enum {@code StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>FAIL = 1;</code>
     */
    FAIL(1),
    /**
     * <code>TIMEOUT = 2;</code>
     */
    TIMEOUT(2),
    /**
     * <code>PARAM_ERROR = 3;</code>
     */
    PARAM_ERROR(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "StatusCode");
    }
    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>FAIL = 1;</code>
     */
    public static final int FAIL_VALUE = 1;
    /**
     * <code>TIMEOUT = 2;</code>
     */
    public static final int TIMEOUT_VALUE = 2;
    /**
     * <code>PARAM_ERROR = 3;</code>
     */
    public static final int PARAM_ERROR_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return FAIL;
        case 2: return TIMEOUT;
        case 3: return PARAM_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.getDescriptor().getEnumType(1);
    }

    private static final StatusCode[] VALUES = values();

    public static StatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StatusCode)
  }

  public interface SyncRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 请求类型/命令
     * </pre>
     *
     * <code>.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * 请求类型/命令
     * </pre>
     *
     * <code>.MessageType type = 2;</code>
     * @return The type.
     */
    com.xbx.study.netty.protobuf.SyncMessageProto.MessageType getType();

    /**
     * <pre>
     * 请求体（业务数据序列化后的字节）
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * 同步请求消息
   * </pre>
   *
   * Protobuf type {@code SyncRequest}
   */
  public static final class SyncRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SyncRequest)
      SyncRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "SyncRequest");
    }
    // Use SyncRequest.newBuilder() to construct.
    private SyncRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SyncRequest() {
      requestId_ = "";
      type_ = 0;
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.class, com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.Builder.class);
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <pre>
     * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_ = 0;
    /**
     * <pre>
     * 请求类型/命令
     * </pre>
     *
     * <code>.MessageType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 请求类型/命令
     * </pre>
     *
     * <code>.MessageType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public com.xbx.study.netty.protobuf.SyncMessageProto.MessageType getType() {
      com.xbx.study.netty.protobuf.SyncMessageProto.MessageType result = com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.forNumber(type_);
      return result == null ? com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 请求体（业务数据序列化后的字节）
     * </pre>
     *
     * <code>bytes payload = 3;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, requestId_);
      }
      if (type_ != com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.MESSAGE_UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, requestId_);
      }
      if (type_ != com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.MESSAGE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest)) {
        return super.equals(obj);
      }
      com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest other = (com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (type_ != other.type_) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 同步请求消息
     * </pre>
     *
     * Protobuf type {@code SyncRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncRequest)
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.class, com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.Builder.class);
      }

      // Construct using com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = "";
        type_ = 0;
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncRequest_descriptor;
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest getDefaultInstanceForType() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest build() {
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest buildPartial() {
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest result = new com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest) {
          return mergeFrom((com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest other) {
        if (other == com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getPayload().isEmpty()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配响应（对应 RequestService.getReqKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 请求类型/命令
       * </pre>
       *
       * <code>.MessageType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 请求类型/命令
       * </pre>
       *
       * <code>.MessageType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型/命令
       * </pre>
       *
       * <code>.MessageType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.MessageType getType() {
        com.xbx.study.netty.protobuf.SyncMessageProto.MessageType result = com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.forNumber(type_);
        return result == null ? com.xbx.study.netty.protobuf.SyncMessageProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 请求类型/命令
       * </pre>
       *
       * <code>.MessageType type = 2;</code>
       * @param value The type to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setType(com.xbx.study.netty.protobuf.SyncMessageProto.MessageType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求类型/命令
       * </pre>
       *
       * <code>.MessageType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 请求体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * 请求体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SyncRequest)
    }

    // @@protoc_insertion_point(class_scope:SyncRequest)
    private static final com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest();
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncRequest>
        PARSER = new com.google.protobuf.AbstractParser<SyncRequest>() {
      @java.lang.Override
      public SyncRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SyncRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xbx.study.netty.protobuf.SyncMessageProto.SyncRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SyncResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SyncResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    java.lang.String getRequestId();
    /**
     * <pre>
     * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes();

    /**
     * <pre>
     * 响应状态
     * </pre>
     *
     * <code>.StatusCode code = 2;</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <pre>
     * 响应状态
     * </pre>
     *
     * <code>.StatusCode code = 2;</code>
     * @return The code.
     */
    com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode getCode();

    /**
     * <pre>
     * 错误信息（code 非 OK 时有值）
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * 错误信息（code 非 OK 时有值）
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * 响应体（业务数据序列化后的字节）
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * <pre>
   * 同步响应消息
   * </pre>
   *
   * Protobuf type {@code SyncResponse}
   */
  public static final class SyncResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SyncResponse)
      SyncResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 0,
        /* suffix= */ "",
        "SyncResponse");
    }
    // Use SyncResponse.newBuilder() to construct.
    private SyncResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SyncResponse() {
      requestId_ = "";
      code_ = 0;
      message_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.class, com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.Builder.class);
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object requestId_ = "";
    /**
     * <pre>
     * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
     * </pre>
     *
     * <code>string request_id = 1;</code>
     * @return The bytes for requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_ = 0;
    /**
     * <pre>
     * 响应状态
     * </pre>
     *
     * <code>.StatusCode code = 2;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     * 响应状态
     * </pre>
     *
     * <code>.StatusCode code = 2;</code>
     * @return The code.
     */
    @java.lang.Override public com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode getCode() {
      com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode result = com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.forNumber(code_);
      return result == null ? com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <pre>
     * 错误信息（code 非 OK 时有值）
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 错误信息（code 非 OK 时有值）
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * 响应体（业务数据序列化后的字节）
     * </pre>
     *
     * <code>bytes payload = 4;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, requestId_);
      }
      if (code_ != com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.OK.getNumber()) {
        output.writeEnum(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, message_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(4, payload_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, requestId_);
      }
      if (code_ != com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, message_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, payload_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse)) {
        return super.equals(obj);
      }
      com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse other = (com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse) obj;

      if (!getRequestId()
          .equals(other.getRequestId())) return false;
      if (code_ != other.code_) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getPayload()
          .equals(other.getPayload())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 同步响应消息
     * </pre>
     *
     * Protobuf type {@code SyncResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SyncResponse)
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.class, com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.Builder.class);
      }

      // Construct using com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        requestId_ = "";
        code_ = 0;
        message_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.internal_static_SyncResponse_descriptor;
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse getDefaultInstanceForType() {
        return com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse build() {
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse buildPartial() {
        com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse result = new com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.requestId_ = requestId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.code_ = code_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.message_ = message_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.payload_ = payload_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse) {
          return mergeFrom((com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse other) {
        if (other == com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse.getDefaultInstance()) return this;
        if (!other.getRequestId().isEmpty()) {
          requestId_ = other.requestId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getPayload().isEmpty()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                requestId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                code_ = input.readEnum();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                message_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                payload_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestId_ = "";
      /**
       * <pre>
       * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return The requestId.
       */
      public java.lang.String getRequestId() {
        java.lang.Object ref = requestId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return The bytes for requestId.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes() {
        java.lang.Object ref = requestId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = getDefaultInstance().getRequestId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求唯一标识，用于匹配请求（对应 RequestService.getRespKey）
       * </pre>
       *
       * <code>string request_id = 1;</code>
       * @param value The bytes for requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        requestId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int code_ = 0;
      /**
       * <pre>
       * 响应状态
       * </pre>
       *
       * <code>.StatusCode code = 2;</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override public int getCodeValue() {
        return code_;
      }
      /**
       * <pre>
       * 响应状态
       * </pre>
       *
       * <code>.StatusCode code = 2;</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应状态
       * </pre>
       *
       * <code>.StatusCode code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode getCode() {
        com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode result = com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.forNumber(code_);
        return result == null ? com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 响应状态
       * </pre>
       *
       * <code>.StatusCode code = 2;</code>
       * @param value The code to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setCode(com.xbx.study.netty.protobuf.SyncMessageProto.StatusCode value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000002;
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应状态
       * </pre>
       *
       * <code>.StatusCode code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * 错误信息（code 非 OK 时有值）
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 错误信息（code 非 OK 时有值）
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 错误信息（code 非 OK 时有值）
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息（code 非 OK 时有值）
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误信息（code 非 OK 时有值）
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        message_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 响应体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <pre>
       * 响应体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @param value The payload to set.
       * @return This builder for chaining.
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        payload_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 响应体（业务数据序列化后的字节）
       * </pre>
       *
       * <code>bytes payload = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000008);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SyncResponse)
    }

    // @@protoc_insertion_point(class_scope:SyncResponse)
    private static final com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse();
    }

    public static com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SyncResponse>
        PARSER = new com.google.protobuf.AbstractParser<SyncResponse>() {
      @java.lang.Override
      public SyncResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SyncResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SyncResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.xbx.study.netty.protobuf.SyncMessageProto.SyncResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SyncResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SyncResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022sync_message.proto\"N\n\013SyncRequest\022\022\n\nr" +
      "equest_id\030\001 \001(\t\022\032\n\004type\030\002 \001(\0162\014.MessageT" +
      "ype\022\017\n\007payload\030\003 \001(\014\"_\n\014SyncResponse\022\022\n\n" +
      "request_id\030\001 \001(\t\022\031\n\004code\030\002 \001(\0162\013.StatusC" +
      "ode\022\017\n\007message\030\003 \001(\t\022\017\n\007payload\030\004 \001(\014*R\n" +
      "\013MessageType\022\023\n\017MESSAGE_UNKNOWN\020\000\022\r\n\tHEA" +
      "RTBEAT\020\001\022\016\n\nUSER_QUERY\020\002\022\017\n\013USER_CREATE\020" +
      "\003*<\n\nStatusCode\022\006\n\002OK\020\000\022\010\n\004FAIL\020\001\022\013\n\007TIM" +
      "EOUT\020\002\022\017\n\013PARAM_ERROR\020\003B0\n\034com.xbx.study" +
      ".netty.protobufB\020SyncMessageProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SyncRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_SyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncRequest_descriptor,
        new java.lang.String[] { "RequestId", "Type", "Payload", });
    internal_static_SyncResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_SyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SyncResponse_descriptor,
        new java.lang.String[] { "RequestId", "Code", "Message", "Payload", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
