server:
  port: 9000
  servlet:
    # 设置响应的字符编码，避免流式返回输出乱码
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: LangChain4J_0

langchain4j:
  http:
    clientBuilderFactory: dev.langchain4j.http.client.spring.restclient.SpringRestClientBuilderFactory
#  open-ai:
#    chat-model:
#      api-key: ${java_deepseek_apikey}
#      model-name: deepseek-v4-flash
#      base-url: https://api.deepseek.com


# 只有日志级别调整为debug级别，同时配置以上 langchain 日志输出开关才有效
logging:
  level:
    dev:
      langchain4j: DEBUG



model:
  qwen:
    video: happyhorse-1.1-r2v
    image: qwen-image-2.0-pro-2026-06-22
    chat: qwen3.7-max-2026-06-08
    embedding: qwen3.7-text-embedding
  deepseek:
    chat: deepseek-v4-pro