server:
  port: 10011

dubbo:
  application:
    name: cloud_dubbo_0
  #注册中心 注册中心置为 N/A，表示不注册
  registry:
    address: N/A
  # 协议配置：使用 triple 协议监听 20880 端口
  protocol:
    port: 20880
    name: tri
  scan:
    base-packages:  com.xbx.study.dubbo.service

logging:
  level:
    org.apache.dubbo: DEBUG