# ========== Scheduler ==========
org.quartz.scheduler.instanceName = MyScheduler
org.quartz.scheduler.instanceId = AUTO

# ========== thread pool ==========
org.quartz.threadPool.class = org.quartz.simpl.SimpleThreadPool
org.quartz.threadPool.threadCount = 10
org.quartz.threadPool.threadPriority = 5

# ========== RAMJobStore (default) ==========
#org.quartz.jobStore.class = org.quartz.simpl.RAMJobStore

# ==========  JDBC JobStore ==========
#org.quartz.jobStore.dataSource = quartzDS
#org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX

# spring local datasource
org.quartz.jobStore.class = org.springframework.scheduling.quartz.LocalDataSourceJobStore

org.quartz.jobStore.driverDelegateClass = org.quartz.impl.jdbcjobstore.StdJDBCDelegate
org.quartz.jobStore.tablePrefix = QRTZ_
org.quartz.jobStore.isClustered = true
org.quartz.jobStore.clusterCheckinInterval = 20000

# ========== DataSource ==============
org.quartz.dataSource.quartzDS.connectionProvider.class = com.xbx.study.web.config.quartz.DruidConnectionProvider
org.quartz.dataSource.quartzDS.driver = com.mysql.cj.jdbc.Driver
org.quartz.dataSource.quartzDS.URL= jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
org.quartz.dataSource.quartzDS.user = root
org.quartz.dataSource.quartzDS.password = mysql
org.quartz.dataSource.quartzDS.maxConnections = 5

