#logging:
#  level:
#    dev:
#      langchain4j: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true
    username: root
    password: mysql
    # Druid 连接池专属配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 开启监控统计和防火墙功能
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 可选：设置监控页面的登录账号密码
        login-username: admin
        login-password: 123456

# MyBatis 配置
mybatis:
  type-aliases-package: com.xbx.study.ai.entity.po

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl





