<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.xbx.study</groupId>
        <artifactId>cloud</artifactId>
        <version>1.0</version>
    </parent>

    <groupId>com.ds</groupId>
    <artifactId>DS</artifactId>
    <packaging>pom</packaging>
    <name>Distributed System</name>

    <modules>
        <module>cloud_admin</module>
        <module>cloud_common</module>
        <module>cloud_dubbo_1</module>
        <module>cloud_dubbo_0</module>
        <module>cloud_gateway</module>
        <module>cloud_web</module>
    </modules>

    <dependencyManagement>

    </dependencyManagement>

    <build>
        <finalName>DS</finalName>
    </build>
</project>
